### ISSUE TITLE
Class 01 - CD2402 Roadmap

### ISSUE THREAD

**Issue by amran75** [IzaanSchool/B2402_CloudComputing_DevOps_Resources#1]
### Topics:
- Introduction to the Course
    - Overview of course objectives and outcomes
    - Importance of Cloud Computing and DevOps in modern IT
- Course Structure and Schedule
    - Breakdown of weekly topics and projects
- Setting Expectations and Goals
    - Discussing the importance of hands-on projects
    - Encouraging active participation and engagement

## Reference
- [Roadmap](https://github.com/IzaanSchool/B2402_CloudComputing_DevOps_Resources/blob/main/RoadMap.md)

## Class Record
-  [Recorded Class Video](https://de5tfr8w5ovjc.cloudfront.net/CD2402/Class_1_27_Aug_2024_230506.mp4)

## Recommendation 

- [Join Slack ](https://join.slack.com/t/izaanschool/shared_invite/zt-1lzi94p93-vdcFNQj29IVEJMCIMOU0Gg)
- Open a [GitHub](https://github.com/signup) Account
- [Open AWS Account ](https://aws.amazon.com/free/)
- Open Free [Loom](https://www.loom.com) Account

# Enroll Now
- Please use this link to finally [enroll](https://www.izaanschool.com/about/fees) to get

**Comment by Jahidul2543** [comment]
# Office Hour  - Interest 8-9 AM CST and 9-10 AM EST

```
Deschiz777@gmail.com, sangjuktaba10@gmail.com, Miraj20@gmail.com
```

**Comment by shamimcloud** [comment]
wao
