### ISSUE TITLE
[Lab] IAM Labs 01

### ISSUE THREAD

**Issue by Jahidul2543** [IzaanSchool/B2402_CloudComputing_DevOps_Resources#4]
# Lab Assignment: AWS IAM and Policy Simulator

## Overview
This lab will give students hands-on experience with AWS Identity and Access Management (IAM). Students will create and manage IAM users, groups, and roles, and use IAM policies to control access to AWS resources. They will also use the IAM Policy Simulator to test and validate their policies.

## Lab Objectives
- Create and manage IAM users, groups, and roles.
- Apply IAM policies to control access to AWS resources.
- Use the IAM Policy Simulator to test and validate policies.

## Lab Steps

1. **Set Up an IAM User**   [Watch Video](https://www.loom.com/share/66d8ea435e824f6a9b0d6f2ea59fd248?sid=566ae4dd-474c-4b85-b5fe-8b10a4007f59)

    - **Objective:** Create an IAM user with specific permissions.
    - **Steps:**
        1. Sign in to the AWS Management Console.
        2. Navigate to the IAM service.
        3. In the left-hand menu, click on "Users".
        4. Click the "Add user" button.
        5. Enter a username (e.g., `student-user`).
        6. Checkbox Select  "Provide user access to the AWS Management Console".
        7. Set a custom password and ensure "Require password reset" is selected.
        8. Click "Next: Permissions".
        9. Select "Attach existing policies directly" and choose the `AmazonS3ReadOnlyAccess` policy.
        10. Click "Next: Tags", add any tags if necessary, then click "Next: Review".
        11. Review the user details and click "Create user".

2. **Create an IAM Group**  [Watch Video](https://www.loom.com/share/cd7d630f47af49f7955d6b1a81df63e9?sid=bf9dfe14-ec6c-49e9-9a0f-4b7e9e71f776)

    - **Objective:** Create an IAM group and add the user to the group.
    - **Steps:**
        1. In the IAM console, click on "Groups" in the left-hand menu.
        2. Click the "Create New Group" button.
        3. Enter a group name (e.g., `student-group`).
        4. Click "Next Step" to attach a policy.
        5. Attach the `AmazonS3ReadOnlyAccess` policy.
        6. Click "Next Step", review the details, and click "Create Group".
        7. Go to the "Users" tab, select the `student-user`, and click "Add user to groups".
        8. Add the user to the `student-group`.

3. **Create an IAM Role**  [Watch Video](https://www.loom.com/share/f3a29ad922504d6c8589c2d0d5bf9fa5?sid=aa872eb0-9a9f-4efd-bd8d-09fd254c2d7c)

    - **Objective:** Create an IAM role for S3 access and use it with the S3 service.
    - **Steps:**
        1. In the IAM console, click on "Roles" in the left-hand menu.
        2. Click the "Create role" button.
        3. Choose "AWS service" and select "S3".
        4. Click "Next: Permissions".
        5. Attach the `AmazonS3FullAccess` policy.
        6. Click "Next: Tags", add any tags if necessary, then click "Next: Review".
        7. Enter a role name (e.g., `S3FullAccessRole`) and click "Create role".

4. **Create and Apply a Custom IAM Policy** [Watch Video](https://www.loom.com/share/98b30907c2f540138e1e76bb2f3c4743?sid=ba0dc59f-91a4-410d-a704-8564bf937121)

    - **Objective:** Create a custom IAM policy and attach it to a user.
    - **Steps:**
        1. In the IAM console, click on "Policies" in the left-hand menu.
        2. Click the "Create policy" button.
        3. Select the "JSON" tab.
        4. Enter the following JSON policy document:
             Example bucket Name: _cd2401-iam-handson-lab_
            ```json
            {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Action": "s3:ListBucket",
                        "Resource": "arn:aws:s3:::example-bucket"
                    },
                    {
                        "Effect": "Allow",
                        "Action": "s3:GetObject",
                        "Resource": "arn:aws:s3:::example-bucket/*"
                    }
                ]
            }
            ```
        5. Click "Review policy".
        6. Enter a name for the policy (e.g., `CustomS3ReadAccess`).
        7. Click "Create policy".
        8. Go to the "Users" tab, select the `student-user`, and click "Add permissions".
        9. Choose "Attach policies directly", find and select the `CustomS3ReadAccess` policy, and click "Next: Review" and then "Add permissions".

5. **Use the IAM Policy Simulator** [watch this video](https://www.loom.com/share/657489e3a2c64e0596c7626ae2309eb4)

    - **Objective:** Test and validate the custom IAM policy using the IAM Policy Simulator.
    - **Steps:**
        1. Go to the [IAM Policy Simulator](https://policysim.aws.amazon.com/).
        2. Select the `student-user` from the list of users.
        3. Select the `CustomS3ReadAccess` policy.
        4. Add actions to simulate, such as `s3:ListBucket` and `s3:GetObject`. 
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "S3ReadAccess",
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:ListBucket"
            ],
            "Resource": "*"
        }
    ]
}
```
        5. If you Specify the resource `arn:aws:s3:::example-bucket` and `arn:aws:s3:::example-bucket/*`. 
let's say our bucket name is  **iam-handson-lab**  [ How to Create a S3 bucket](https://www.loom.com/share/dd67d36347404b82b3b402bd2a4cfbb6?sid=ed1cb994-491b-4b23-91af-6dee6d49bb92) 

  ```
  {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::example-bucket"
        },
        {
            "Effect": "Allow",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::example-bucket/*"
        }
    ]
}
  
  ```

        6. Click "Run Simulation".
        7. Review the results to ensure the policy allows the intended actions and denies others.

## Lab Summary
By completing this lab, students will gain practical experience with AWS IAM, including creating and managing users, groups, and roles, and applying policies to control access. They will also learn how to use the IAM Policy Simulator to test and validate their policies.

## Deliverables
- Screenshot of the created IAM user and assigned permissions.
- Screenshot of the IAM group and the added user.
- Screenshot of the IAM role.
- Screenshot of the custom IAM policy.
- Screenshot of the IAM Policy Simulator results.

- **Recommended Reading:**
  - [ ] [AWS IAM Documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/introduction.html)
  - [ ] [AWS IAM Best Practices](https://aws.amazon.com/iam/best-practices/)

- **Online Resources:**
  - [ ] [AWS IAM User Guide](https://docs.aws.amazon.com/IAM/latest/UserGuide/)
  - [ ] [AWS IAM Policy Simulator](https://policysim.aws.amazon.com/)

**Comment by Jahidul2543** [comment]
@IzaanSchool/cd-2402  Please use this ticket and try to do this Lab. Please use slack channel to request help.
Thanks

**Comment by Jahidul2543** [comment]
Here is my lab [work](https://github.com/IzaanSchool/CloudComputingDevOpsStudentsTaskTracker/issues/158)

**Comment by nabilasaeed** [comment]
![create groups](https://github.com/user-attachments/assets/9628c703-f8a4-4411-9753-c2299346f2db)

**Comment by nabilasaeed** [comment]
![creating group](https://github.com/user-attachments/assets/4453650c-20f4-426a-9a7b-47da71ac62da)

**Comment by nabilasaeed** [comment]
![creating policy](https://github.com/user-attachments/assets/c0e28f8e-3551-4a55-9276-d7bcd487d500)

**Comment by nabilasaeed** [comment]
here is my lab [work](https://github.com/IzaanSchool/CloudComputingDevOpsStudentsTaskTracker/issues/163)
